### ISSUE TITLE
Input prompt takes last answer on Nodejs 4.0.0

### ISSUE THREAD

**Issue by rosen-vladimirov** [SBoudrias/Inquirer.js#282] opened 2015-09-09 17:44 UTC
Hi,

I've just tried using inquirer with latest Node - 4.0.0 and I've found an issue with consecutive input prompts. Here's the test case:
```JavaScript
var inquirer = require("inquirer");
var question1 = {
	type: "input",
	message: "Enter something: ",
	name: "Failing_Node_4.0.0"
}

inquirer.prompt([question1], function( answers ) {
    // Use user feedback for... whatever!!
    console.log("First inquirer answered:", answers);
});

inquirer.prompt([question1], function( answers ) {
    // Use user feedback for... whatever!!
    console.log("Second inquirer answered:", answers);
});
```

When I enter some value in the first prompt, my answer is used for it and for the second input, so it is automatically resolved. I've tried this on Windows (cmd and Git Bash) and on Linux.
Same issue is reproduced with iojs 3.3.0 (tested on Linux only).

**Comment by SBoudrias** [comment] 2015-09-09 18:36
Inquirer is asynchronous. You cannot run two prompt at the same time.

**Comment by rosen-vladimirov** [comment] 2015-09-09 20:41
Hi @SBoudrias ,
Thanks for pointing this. However we are using inquirer in synchronous code (by using fibers) and as I've tried to simplify the repro case, I've made mistake in the script that I've sent you. Here is the correct one:
```JavaScript
var inquirer = require("inquirer");
var question1 = {
    type: "input",
    message: "Enter something: ",
    name: "Failing_Node_4.0.0"
}

inquirer.prompt([question1], function( answers ) {
    // Use user feedback for... whatever!!
    console.log("First inquirer answered:", answers);

    inquirer.prompt([question1], function( answers ) {
        // Use user feedback for... whatever!!
        console.log("Second inquirer answered:", answers);
    });
});
```
It is working fine on Node 0.12.x, but not on Node 4.0.0. The second inquirer calls the answers callback and accepts the same answer. After that the console is not released, it keeps waiting for input I think.

**Comment by rosen-vladimirov** [comment] 2015-09-09 20:45
Just to add something - the second inquirer **does not accept** the same answer - it receives empty string as an answer.

**Comment by lsycxyj** [comment] 2015-09-13 03:43
A bug similar to it. It works fine except Node 4.0.0. Arrow keys does not work in windows prompt.

```javascript
  var inquirer = require('inquirer');
  inquirer.prompt([
    {
      type: "list",
      name: 'test',
      message: "test?",
      choices: [
        'A',
        new inquirer.Separator(),
        'B',
        new inquirer.Separator(),
        'C'
      ]
    }
  ]);
```

**Comment by Awk34** [comment] 2015-09-13 22:31
I have the same issue. I was trying to install Semantic UI, which uses [gulp-prompt](https://github.com/Freyskeyd/gulp-prompt) which in turn uses Inquirer.js. My solution was to use Node.js 0.12.7 via [nvm-windows](https://github.com/coreybutler/nvm-windows), install Semantic UI, and then go back to using Node 4.0.0.

**Comment by SBoudrias** [comment] 2015-09-14 04:35
Hey guys, I'll need more details because I just tested this on Window 10 (cmd.exe and Node 4.0) and everything is working fine.

I also copied your code example verbatim and it's working fine.

So please retry with the latest Inquirer version. Then give me:

1. Code that I can run and that is failing for you on your computer.
2. Windows version
3. Node version
4. Inquirer.js version
5. Command line used to reproduce the bug

**Comment by LPGhatguy** [comment] 2015-09-14 16:56
@Awk34 @lsycxyj that issue is reported for Windows at issue #266.

**Comment by magnis** [comment] 2015-09-25 20:40
This worked great on `v0.12.x`, but not on `v4.x.x`:

```
var inquire = require('inquirer');
var childProcess = require('child_process');

var chooseList = {
	type: "list",
	name: "whichProcess",
	message: "Which process to run?",
	choices: ["Option 1", "Option  2", "Option  3", "Option  4", "Option  5"]
}

inquire.prompt(chooseList, function (prompts) {
	switch (prompts.whichProcess) { //etc
```

**Comment by SBoudrias** [comment] 2015-09-27 04:02
I'm going to close this issue as #266 have more feedback and is tracking the issue on Node side. Please continue further conversation over there.

**Closed by SBoudrias** 2015-09-27 04:02 UTC
Labels: bug

**Comment by johnweland** [comment] 2015-12-02 03:50
I actually have the same issue in Node 5.1.0

**Comment by ericis** [comment] 2016-02-10 20:39
Same. I also have the issue on Node 5.6.0

**Comment by kascode** [comment] 2016-06-07 17:44
Same issue. Node v.5.11.0

**Comment by projer** [comment] 2016-06-23 10:19
Same issue with 5.10.1 here
