### ISSUE TITLE
MaxListenersExceededWarning in Windows

### ISSUE THREAD

**Issue by dantasfiles** [SBoudrias/Inquirer.js#887] opened 2020-02-01 23:00 UTC
I run [packages/inquirer/examples/recursive.js](https://github.com/SBoudrias/Inquirer.js/blob/master/packages/inquirer/examples/recursive.js). 
In 7.0.4 (latest) on Windows, I get a MaxListenersExceededWarning:
```
> node recursive.js
? What's your favorite TV show? 1
? Want to enter another TV show favorite (just hit enter for YES)? Yes
? What's your favorite TV show? 2
? Want to enter another TV show favorite (just hit enter for YES)? Yes
? What's your favorite TV show? 3
? Want to enter another TV show favorite (just hit enter for YES)? Yes
? What's your favorite TV show? 4
? Want to enter another TV show favorite (just hit enter for YES)? Yes
? What's your favorite TV show? 5
? Want to enter another TV show favorite (just hit enter for YES)? Yes
? What's your favorite TV show? 6
? Want to enter another TV show favorite (just hit enter for YES)? Yes
? What's your favorite TV show? 7
? Want to enter another TV show favorite (just hit enter for YES)? Yes
? What's your favorite TV show? 8
? Want to enter another TV show favorite (just hit enter for YES)? Yes
? What's your favorite TV show? 9
? Want to enter another TV show favorite (just hit enter for YES)? Yes
? What's your favorite TV show? (node:40212) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [ReadStream]. Use emitter.setMaxListeners() to increase limit
(node:40212) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 keypress listeners added to [ReadStream]. Use emitter.setMaxListeners() to increase limit    
? What's your favorite TV show? 10
? Want to enter another TV show favorite (just hit enter for YES)? No
Your favorite TV Shows: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
```

The MaxListenersExceededWarning occurs in **7.0.4** and **7.0.2**

It does *not* occur in **7.0.3** and **<=7.0.1**.

My environment is
```
 System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 1.19 GB / 7.85 GB
  Binaries:
    Node: 13.7.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.6 - C:\Program Files\nodejs\npm.CMD
```

**Comment by attilah** [comment] 2020-02-27 01:52
@SBoudrias I've diagnosed this issue while trying to fix it in Amplify CLI where we're leveraging Inquirer to drive the console prompts.
The root cause is that every prompt creates a new RXJS Observable to the process' stdin, and event based observables can only be released if they're subscribed and the subscription's unsubscribe method is called. Since inquirer only using RXJS operators it does not happen. Only the Editor prompt uses subscription, but only for the `line` and not for `keypress`. A single prompt or a prompt list lifecycle could handle it in a clean way, the very same way as Editor does, unsubscribed from `keypress` in `onEnd` handler. Since the same problem exist in extensions it would be better to handle in a higher level.
Another solution would be to just create the Observable object once and reuse it between prompts as stdin "rarely changes", but `events.js` could manage a list of `rl` objects and hand over the proper observable based on the `rl` object reference. /cc @dantasfiles

**Comment by rizzlesauce** [comment] 2020-03-04 06:52
@SBoudrias is it possible that this bug is caused by https://github.com/SBoudrias/Inquirer.js/pull/882 (https://github.com/SBoudrias/Inquirer.js/pull/882/commits/03412e5c0b1c9eb2ad8d559bfcc29b5cf7e8575c)? It appears that change makes it so that the readline interface does not get closed on windows.

**Comment by SBoudrias** [comment] 2020-03-04 13:24
@rizzlesauce that's possible; but closing the readline on windows was making the prompt unresponsive.

The best solution on the longer term is probably moving away from rxjs altogether. I've made a lot of progress on this https://github.com/SBoudrias/Inquirer.js/issues/692 - but I'm running out of time to complete a release.

I'm okay to review a PR if anyone wants to take the time.

**Comment by nanomosfet** [comment] 2022-04-05 15:43
this is happening in 7.3.3 of inquierer

going to have to move off this package for this reason

**Comment by SBoudrias** [comment] 2022-04-05 16:28
@nanomosfet take a look at the `@inquirer/*` prompts (https://github.com/SBoudrias/Inquirer.js/tree/master/packages/input and the other). They're simpler interfaces and should be faster. All core prompts are already re-implemented in that fashion, checkout the other packages in the monorepo to see them all.

**Comment by Kief5555** [comment] 2022-07-22 01:31
I am getting memory leaks on 8.2.4 on trace it seems like `NXJS` is cauing this issue.

**Comment by SBoudrias** [comment] 2022-07-22 15:04
Yeah, `rxjs` has been a problematic dependency for memory leaks. Like I said, the new prompts under the `@inquirer/*` namespace aren't relying on it for this reason; and they're available on npm if you want to give them a try.

**Comment by Kief5555** [comment] 2022-07-22 15:06
Hi,

Can I have a direct link?
Also I cannot inquirer due to the fact I have using pkg package to distribute my app, pkg does not support esm

**Comment by SBoudrias** [comment] 2022-07-22 15:15
Over here: https://www.npmjs.com/search?q=%40inquirer

**Comment by ethereal-engineer** [comment] 2023-02-14 02:52
This is also happening on Linux, but it has been fine until recently so I am not entirely sure what happened.

**Comment by blade2005** [comment] 2023-04-20 23:23
Getting this error on wsl2 as well.

**Comment by SBoudrias** [comment] 2023-06-03 21:12
Closing this ticket as stale. Open new issues if you encounter problems with the [new Inquirer API](https://github.com/SBoudrias/Inquirer.js/issues/293#1214).

**Closed by SBoudrias** 2023-06-03 21:12 UTC
