### ISSUE TITLE
Simple enhancement: pass Paginator page height as option

### ISSUE THREAD

**Issue by dthree** [SBoudrias/Inquirer.js#295] opened 2015-10-12 03:32 UTC
Right now the Paginator `pageSize` variable is [hardcoded at a fixed 7](https://github.com/SBoudrias/Inquirer.js/blob/master/lib/utils/paginator.js#L18).

Sometimes, a ton of stuff gets listed, and the auto-scrolling is just a littel rough at that small a size.

Would it be possible to pass in an option to `inquirer.prompt` to set a custom paginator size? This seems like a very simple enhancement.

**Comment by sindresorhus** [comment] 2015-10-20 20:43
:+1:

**Comment by mrkev** [comment] 2015-10-31 03:09
+1

**Comment by SBoudrias** [comment] 2015-11-06 03:50
Fixed with #300 

Also a duplicate of #180

**Closed by SBoudrias** 2015-11-06 03:50 UTC

**Comment by dthree** [comment] 2015-11-06 04:59
:+1: thanks!

**Comment by mrkev** [comment] 2015-11-06 07:04
awesome thanks!
