### ISSUE TITLE
Support mintty on MINGW64

### ISSUE THREAD

**Issue by TicoDePano** [SBoudrias/Inquirer.js#621] opened 2017-12-13 22:38 UTC
Mintty is installed along with Git for Windows.

Is there any chance to support mintty?

**Comment by kbrandwijk** [comment] 2018-01-10 05:57
I don't have issues with mintty on Windows.

**Comment by sunrize531** [comment] 2019-02-25 10:36
I can confirm that in mintty moving the cursor with arrows in prompts doesn't work at all.

**Comment by sunrize531** [comment] 2019-02-26 10:27
So, more info on this. When script with inquirer prompt in it called directly - it works perfectly fine in mintty too. But if the same script called via `npm run` in mintty running gitbash - it's completely screwed. Arrows don't work, you can't even close it with Ctrl-C and also the output lacks colours. Probably something to do with stdout/stdin pipes in mintty.

**Comment by bitmvr** [comment] 2019-03-20 15:13
I can second what @sunrize531 mentioned above.

If Inquirer is using `prompts`, this thread may be of value.
> https://github.com/terkelg/prompts/pull/36

**Comment by Zamiell** [comment] 2020-10-19 00:15
using this on Git Bash for Windows also duplicates the questions, making the library unusable

e.g.

```
? Would you like to create a config file? (Y/n)    # press enter to continue
? Would you like to create it now? Yes
```

**Comment by Zamiell** [comment] 2020-10-19 00:51
looks like this is related to #432

**Comment by Zamiell** [comment] 2021-12-08 16:47
I noticed that Inquirer was NOT duplicating text in a simple test repository, but was duplicating text in my real app, so I did some investigating.

The issue seems to be because:
- when you type `npx foo`
- it invokes a shell script located at `C:\Users\[Username]\AppData\Roaming\npm\foo.cmd`
- which contains a line that invokes node like this:

```
endLocal & goto #_undefined_# 2>NUL || title %COMSPEC% & "%_prog%"  "%dp0%\node_modules\test\dist\main.js" %*`
```

Essentially, this command ends up up being: `"node" "path/to/foo.js"`

When I take off the quotation marks around the "node" command, the bug seems to go away, as demonstrated by the following screenshot:

![image](https://user-images.githubusercontent.com/5511220/145247765-ad6d4295-c8aa-4232-a129-b480a93a3904.png)

Pardon my French, but why the fuck is this happening? Why does putting quotation marks around node change the behavior of the resulting program? And is there some kind of fix that I can include in my JavaScript code to work around this problem?

**Comment by lbglb** [comment] 2023-04-20 13:36
> Why does putting quotation marks around node change the behavior of the resulting program?

`node` will respect the `alias` if there is one (check by running `alias node`).. `"node"` ignores the `alias`.

**Comment by SBoudrias** [comment] 2024-04-04 21:11
Anyone narrowed down exactly what happens and how to fix/run the script with proper streams and/or interactive tty?

I'd be happy to document this in the README to help anyone running into this issue in the future.

**Closed** 2024-08-18 19:32 UTC
