### ISSUE TITLE
Asynchronous validation functions causing missed input

### ISSUE THREAD

**Issue by malee31** [SBoudrias/Inquirer.js#1073] opened 2021-12-28 07:05 UTC
May be related to Issue #912 
I noticed that after running a prompt with an asynchronous validate function, a following prompt will miss a line of input and require input twice due to the first line being ignored.

I wrote a simple script with this behavior and attached it below. The first two prompts will run fine but the final one (must type "done" into it) will miss the first line of input. Pressing an arrow/any key after pressing enter will cause the prompt to re-render and wait for a proper answer again.

Device details:
OS: Windows 11
Terminal: PowerShell
Node: 16.13.1
Inquirer: ^8.2.0 (current latest)

```js
const inquirer = require("inquirer");

async function sleep(time) {
	return new Promise(resolve => setTimeout(resolve, time));
}

(async() => {
	let res = await inquirer.prompt({
		name: "val",
		message: "Prompt 1 - Press Anything",
		type: "input",
		validate: async() => {
			await sleep(1000);
			return true;
		}
	});
	console.log(`Result 1: [${res.val}]`);

	res = await inquirer.prompt({
		name: "val",
		message: "Prompt 2 - Press Anything",
		type: "input"
	});
	console.log(`Result 3: [${res.val}]`);

	res = await inquirer.prompt({
		name: "done",
		message: "Prompt 3 - Type done",
		type: "input",
		validate: async val => {
			await sleep(1000);
			return val.toLowerCase() === "done";
		}
	});
	console.log(`Result 3: [${res.done}]`);
})();
```

Result as a screenshot<br>
![image](https://user-images.githubusercontent.com/43216761/147537884-c00b670f-9945-47be-8b26-85c7219a6e0f.png)

**Comment by ovidiu141** [comment] 2024-09-07 13:31
Could not reproduce with "inquirer": "^10.2.1". 
I think this was somehow fixed and should probably close this one. 
And also probably https://github.com/SBoudrias/Inquirer.js/issues/912 should also be closed.

**Comment by SBoudrias** [comment] 2024-09-07 18:37
Thanks for the help clearing old issues @ovidiu141 - I appreciate it!

**Closed by SBoudrias** 2024-09-07 18:37 UTC
Labels: bug, good first issue
