### ISSUE TITLE
How to clear the terminal after each prompt?

### ISSUE THREAD

**Issue by gotofritz** [SBoudrias/Inquirer.js#915] opened 2020-04-28 12:19 UTC
Hi, thanks for the free tool.

Is there a built-in way to clear the terminal before each question and put the prompt at the top of the terminal? Thanks

**Comment by mischah** [comment] 2020-04-28 13:30
He @gotofritz,

this is duplicate of #746 

Cheers, Michael

**Closed by mischah** 2020-04-28 13:30 UTC
Labels: duplicate
