### ISSUE TITLE
List questions type does not allow navegation on git bash

### ISSUE THREAD

**Issue by emartinpi** [SBoudrias/Inquirer.js#921] opened 2020-05-24 11:06 UTC
**Observed behavior**
List questions display a list but arrow keys do not navigate between options (visually), although in an "invisible way" you can select an option. Enter does proceed to the next question with the "invisible option"

**Expected behavior**
List questions display a list that can be visually interacted with and select the desired option

**Version information**
inquirer@7.1.0
node@12.10.0
command line @ git bash on windows (installed with git)
windows @ Windows 10 Enterprise

**Comment by remiX-** [comment] 2020-06-03 14:18
+1 

I've noticed this for a while, especially with using yeoman generators.

On my journey of googling to try find if it is fixed or a way around it but lead my here

**Comment by 1ak31sha** [comment] 2020-06-18 17:50
I am having same issue
using the fish shell on mac

**Comment by SBoudrias** [comment] 2020-07-13 17:11
Hi all,

"Git bash" on Windows is one of the rare terminals we cannot support. The problem is it is not a true interactive terminals which makes it incompatible with the redrawing of the screen inquirer is doing.

I believe there's now many good alternatives and built-in terminals in windows nowaday. I would recommend you using those instead. Personally back in the days I used powershell on Windows, it wasn't bash based, but other than that it was pretty good.

I'll close this ticket as there's unfortunately nothing we can do to support git bash.

**Closed by SBoudrias** 2020-07-13 17:11 UTC

**Comment by marknadig** [comment] 2022-02-08 17:17
Appreciate any suggestions on how to detect git bash so I can provide a helpful warning in our script.
