### ISSUE TITLE
Node 8.1 breaks Inquirer.js: Hangs on nested calls

### ISSUE THREAD

**Issue by jtillmann** [SBoudrias/Inquirer.js#547] opened 2017-06-09 11:51 UTC
The latest version of Node, 8.1, breaks the behavior when using nested/subsequent calls. 

The existing example 'nested-calls.js' shows this behavior: The second prompt is displayed, but unresponsive. 

Node 8.0 still works, it may have something to do with [the change regarding async hooks](https://nodejs.org/en/blog/release/v8.1.0/).

**Comment by LeonBlade** [comment] 2017-06-09 11:57
I also just encountered this issue as you made this issue coincidentally enough.

**Comment by not-an-aardvark** [comment] 2017-06-10 03:54
This is probably caused by https://github.com/nodejs/node/issues/13557.

**Comment by RileyIO** [comment] 2017-06-17 17:04
Just encountered this issue on node v8.1.0, upgraded to v8.1.2 and the issue went away.

**Comment by SBoudrias** [comment] 2017-06-18 06:04
Thanks for updating the thread! I'll close this issue.

**Fix**: Upgrade to at least Node v8.1.2

**Closed by SBoudrias** 2017-06-18 06:04 UTC
