### ISSUE TITLE
Error handler callback

### ISSUE THREAD

**Issue by iongion** [SBoudrias/Inquirer.js#363] opened 2016-04-21 08:49 UTC
I do not know if this is the expected behavior, but I am having trouble handling the errors, I want to display the user an input that if invalid, will display an error and retry otherwise continue, what I am doing is this("inquirer": "1.0.2"):

```
function asumeRole(cb) {
  const prompt = {
    name: 'MFA',
    type: 'input',
    message: 'Please enter the generated MFA code',
    validate: function validate(response) {
      const done = this.async();
      if (response.length === 0) {
        done('The MFA code cannot be empty');
      } else {
        done(null, response);
      }
    }
  };
  inquirer.prompt([prompt])
  .then((response) => {
    console.log('got response', response);
  })
  .catch((error) => {
    console.log('got error', error);
  });
}
gulp.task('deploy', [], (cb) => {
  asumeRole((mfaCode) => {
    console.log('using mfa code', mfaCode);
  });
});
```

The done callback with error is called but then the catch is never called rendering impossible to do something on error except then bailing out.

The output looks like this:

```
? Please enter the generated MFA code
W:\Workspace\MyProject\node_modules\rx\dist\rx.js:77
    throw e;
    ^
 The MFA code cannot be empty
```

**Comment by SBoudrias** [comment] 2016-04-21 17:50
Yes, failing validation doesn't fail the prompt. It warn the users and ask a valid answer.

**Comment by zckrs** [comment] 2016-05-31 13:35
Same issue. 

```
validate(input) {
        return new Promise((resolve, reject) => {
          console.log(input);
          reject('Wrong choices. You should select other choice!');
        });
      }
```

Output:
```
/home/zckrs/.nvm/versions/node/v6.2.0/lib/node_modules/yo/node_modules/rx/dist/rx.js:77
    throw e;
    ^
Wrong choices. You should select other choice!
                                                                                                                                                                                                                   
project7 git/master  
❯ 

```

How can we reject user choices without stop process ?

**Comment by SBoudrias** [comment] 2016-05-31 17:57
@zckrs so you're saying rejecting the promise end up throwing an unhandled error?

With every prompt? Only one prompt? Please give me more context + code example if possible.

**Comment by zckrs** [comment] 2016-06-01 10:13
Sorry for missing informations

I edit the first prompt in [examples/list.js](https://github.com/SBoudrias/Inquirer.js/blob/master/examples/list.js#L23) 

```
/**
 * List prompt example
 */

'use strict';
var inquirer = require('..');

inquirer.prompt([
  {
    type: 'list',
    name: 'theme',
    message: 'What do you want to do?',
    choices: [
      'Order a pizza',
      'Make a reservation',
      new inquirer.Separator(),
      'Ask for opening hours',
      {
        name: 'Contact support',
        disabled: 'Unavailable at this time'
      },
      'Talk to the receptionist'
    ],
    validate(input) { // <========= add validate
      return new Promise((resolve, reject) => {
        console.log(`\n${input}`);
        reject('Wrong choices. You should select another choice!');
      });
    }
  },
  {
    type: 'list',
    name: 'size',
    message: 'What size do you need?',
    choices: ['Jumbo', 'Large', 'Standard', 'Medium', 'Small', 'Micro'],
    filter: function (val) {
      return val.toLowerCase();
    }
  }
]).then(function (answers) {
  console.log(JSON.stringify(answers, null, '  '));
});
```

Output
```
Inquirer.js/examples git/master*  
❯ node list.js
? What do you want to do? (Use arrow keys)
❯ Order a pizza 
  Make a reservation 
  ──────────────
  Ask for opening hours 
  - Contact support (Unavailable at this time)
  Talk to the receptionist 
Order a pizza



/home/zckrs/github/Inquirer.js/node_modules/rx/dist/rx.js:77
    throw e;
    ^
Wrong choices. You should select other choice!

```
And process is finished.


For other question type like "input", "checkbox", "password" and "rawlist"  validate function works as expected

**Comment by SBoudrias** [comment] 2016-07-04 22:05
This appears to be a duplicate of the clearer issue #383 - I'll close in favor of that other one.

**Comment by rclark** [comment] 2016-08-10 02:15
Here's a very simplified case:

```js
var inquirer = require('inquirer');

inquirer.prompt({
    type: 'input',
    name: 'data',
    message: 'tell me:',
    filter: function(data) {
        var cb = this.async();
        cb(new Error('oopsies'));
    }
}).then(function(answers) {
    console.log(answers);
}, function(err) {
    console.log('we died! %s', err);
});
```

I would expect to be able to somehow handle an error that may occur during an async validate or filter operation. Instead, we end up throwing an exception that is unrecoverable.

**Closed** 2024-08-18 20:27 UTC
